---
name: Create Docker Image on Release and upload to the GitHub registry

on:  # yamllint disable-line rule:truthy
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          VERSION=${{ github.event.release.tag_name }}
          docker build -t $IMAGE_NAME:$VERSION --build-arg version=$VERSION .
          docker push $IMAGE_NAME:$VERSION

      - name: Cleanup old Docker images (keep 3 latest)
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'playground'
          package-type: 'container'
          min-versions-to-keep: 3
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore-versions: 'v[0-9]+.[0-9]+rc[0-9]+'

      - name: Cleanup old pre-release Docker images (keep 3 latest)
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'playground'
          package-type: 'container'
          min-versions-to-keep: 3
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore-versions: 'v[0-9]+.[0-9]+.[0-9]+'
